### ISSUE TITLE
fix container building

### ISSUE THREAD

**Issue by martenson** [RECETOX/chem_identifier_converter#1]
logs are at https://hub.docker.com/repository/registry-1.docker.io/recetox/chem_identifier_converter/builds/eb94a664-0db4-4e5f-8e05-f3f791b71ae7

**Comment by ondrejme** [comment]
I tried to build the docker image locally and it worked, so I ran the build on dockerhub again and this time it passed.
https://hub.docker.com/repository/registry-1.docker.io/recetox/chem_identifier_converter/timeline

**Comment by martenson** [comment]
Sounds great!
